services:
  my.new.solution.milestone.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8082:8080"

  my.new.solution.milestone.worker:
    environment:
      - DOTNET_ENVIRONMENT=Docker
    # ports:
    #   - "8081:8080"
