apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-new-solution.fullname-api" . }}
  labels:
    {{- include "my-new-solution.labels-api" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.api.enabled }}
  replicas: {{ .Values.replicaCount.api }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "my-new-solution.selectorLabels-api" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations.api }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "my-new-solution.labels-api" . | nindent 8 }}
        {{- with .Values.podLabels.api }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "my-new-solution.serviceAccountName-api" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext.api | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository.api }}:{{ .Values.image.tag.api | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.api.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe.api | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.api | nindent 12 }}
          resources:
            {{- toYaml .Values.resources.api | nindent 12 }}
          {{- with .Values.volumeMounts.api }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes.api }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector.api }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.api }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.api }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
