{{- if .Values.autoscaling.api.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "my-new-solution.fullname-api" . }}
  labels:
    {{- include "my-new-solution.labels-api" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "my-new-solution.fullname-api" . }}
  minReplicas: {{ .Values.autoscaling.api.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.api.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.api.targetCPUUtilizationPercentage }}
    - type: ContainerResource
      containerResource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.api.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.api.targetMemoryUtilizationPercentage }}
    - type: ContainerResource
      containerResource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.api.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
