{{- if .Values.serviceAccount.worker.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-new-solution.serviceAccountName-worker" . }}
  labels:
    {{- include "my-new-solution.labels-worker" . | nindent 4 }}
  {{- with .Values.serviceAccount.worker.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.worker.automount }}
{{- end }}
