apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-new-solution.fullname-api" . }}
  labels:
    {{- include "my-new-solution.labels-api" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "my-new-solution.selectorLabels-api" . | nindent 4 }}
