{{- if .Values.istio.api.enabled -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "my-new-solution.fullname" . }}
  labels:
    {{ include "my-new-solution.labels" . | nindent 4 }}
spec:
  hosts:
  {{ range .Values.istio.api.hosts }}
    - {{ . }}
  {{- end }}
  gateways:
  - {{ .Values.istio.api.gateway }}
  http:
  - name: "all-routes"
    match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ .Values.service.api.name }}
        # host: {{ printf "%s.%s.svc.cluster.local" .Values.service.name .Release.Namespace }}
        # subsets: {{ include "my-new-solution.fullname" . }}
        port: 
          number: {{ .Values.service.api.port | int }}
{{- end }}